services:
  promtail:
    container_name: abelo-promtail
    image: grafana/promtail:3.0.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro # Для Linux: доступ к логам докера
      - /var/run/docker.sock:/var/run/docker.sock:ro # Доступ к API докера для чтения логов всех контейнеров
      - ./observability/promtail/config.yaml:/etc/promtail/config.yaml:ro # Конфиг Promtail
      - promtail-positions:/tmp/positions # Позиции чтения (чтобы помнить, где остановился)
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      - abelo_network
    restart: unless-stopped

volumes:
  promtail-positions:
    driver: local
