services:
  load-test:
    container_name: load-test
    profiles:
      - load-test
    image: williamyeh/wrk
    command: [ "-t", "6", "-c", "96", "-d", "600s", "--latency", "http://abelo-app:8000/message/069d7707-f1c7-7835-8000-016faf774cf3" ]
    depends_on:
      abelo-app:
        condition: service_started
    network_mode: service:abelo-app
