x-security-defaults: &security-defaults
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

services:
  prometheus:
    container_name: abelo-prometheus
    image: prom/prometheus:v2.51.0
    <<: *security-defaults
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      #- '--storage.tsdb.retention.time=15d' # ограничиваем размер WAL, чтобы не забивать диск
    networks:
      - abelo_network
    restart: unless-stopped
    depends_on:
      - node-exporter
      - abelo-app
      - statsd-exporter
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M

volumes:
  prometheus-data:
    driver: local
