[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = true

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  path = "/metrics"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "5s"