groups:
  - name: abelo_alerts
    rules:
      - alert: HighRequestLatency
        expr: |
          histogram_quantile(0.95, 
            sum by (le, method) (
              rate(http_request_duration_seconds_bucket{job="statsd-exporter"}[5m])
            )
          ) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "Алерт на высокую задержку (P95 > 1 секунды) 95th percentile latency is above 1s for method {{ $labels.method }}. Current value: {{ $value }}s"

      - alert: HighErrorRate
        expr: |
          sum by (method) (
            rate(http_requests_total{job="statsd-exporter", status_code=~"5.."}[5m])
          )
          /
          sum by (method) (
            rate(http_requests_total{job="statsd-exporter"}[5m])
          ) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 5xx error rate"
          description: "Алерт на ошибки (5xx) Error rate is {{ $value | humanizePercentage }} for method {{ $labels.method }}"