groups:
  - name: abelo_alerts
    rules:
      - alert: HighRequestLatency
        expr: |
          histogram_quantile(0.95, 
            sum by (le, path) (
              rate(http_request_duration_seconds_by_path_bucket{job="statsd-exporter"}[1m])
            )
          ) >= 0.5
        for: 1s
        labels:
          severity: warning
        annotations:
          summary: "High latency detected (>0.5s)"
          description: "95th percentile latency is above 0.5s for path {{ $labels.path }}. Current value: {{ $value }}s"

      - alert: HighErrorRate
        expr: |
          sum by (method) (
            rate(http_requests_total{job="statsd-exporter", status_code=~"5.."}[5m])
          )
          /
          sum by (method) (
            rate(http_requests_total{job="statsd-exporter"}[5m])
          ) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 5xx error rate"
          description: "Error rate is {{ $value | humanizePercentage }} for method {{ $labels.method }}"