{
 "title": "Abelo Monitoring",
 "tags": [
  "abelo",
  "fastapi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])" }
   ]
  },
  {
   "title": "Latency P95",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"abelo-app\"}"
    }
   ]
  },
  {
   "title": "Application Logs (Structlog)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"abelo-app\"}"
    }
   ]
  }
 ]
}